version: '3'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_INITDB_ROOT_USERNAME=mongorootuser
      - MONGO_INITDB_ROOT_PASSWORD=mongorootpw
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./import-sample-data.sh:/docker-entrypoint-initdb.d/import-sample-data.sh:ro
      - ./listingsAndReviews.json:/listingsAndReviews.json:ro
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongorootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongorootpw
    ports:
      - 8081:8081
    restart: unless-stopped
